import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const additionalCareers = [
  // Additional Healthcare Careers
  {
    title: 'Anesthesiologist',
    description: 'Physicians who administer anesthetics and analgesics for pain management before, during, or after surgery.',
    avgSalary: '$331,190',
    salaryRange: '$208,000 - $400,000+',
    requirements: 'Medical degree (M.D. or D.O.) and residency in Anesthesiology',
    education: 'Doctoral degree',
    growth: 'Average (2%)',
    onetCode: '29-1211.00',
  },
  {
    title: 'Psychiatrist',
    description: 'Diagnose, treat, and help prevent mental disorders. They prescribe medication and provide therapy.',
    avgSalary: '$217,100',
    salaryRange: '$130,000 - $300,000+',
    requirements: 'Medical degree and psychiatry residency',
    education: 'Doctoral degree',
    growth: 'Faster than average (12%)',
    onetCode: '29-1223.00',
  },
  {
    title: 'Optometrist',
    description: 'Diagnose, manage, and treat conditions and diseases of the eye and visual system.',
    avgSalary: '$124,300',
    salaryRange: '$68,000 - $200,000',
    requirements: 'Doctor of Optometry (O.D.) degree',
    education: 'Doctoral degree',
    growth: 'Faster than average (9%)',
    onetCode: '29-1041.00',
  },
  {
    title: 'Chiropractor',
    description: 'Diagnose and treat patients with health problems of the musculoskeletal system and treat the effects of those problems on the nervous system.',
    avgSalary: '$75,380',
    salaryRange: '$38,000 - $150,000',
    requirements: 'Doctor of Chiropractic (D.C.) degree',
    education: 'Doctoral degree',
    growth: 'Faster than average (10%)',
    onetCode: '29-1011.00',
  },
  {
    title: 'Dietitian',
    description: 'Plan and conduct food service or nutritional programs to help people lead healthy lives.',
    avgSalary: '$61,650',
    salaryRange: '$40,000 - $89,000',
    requirements: "Bachelor's degree in Dietetics and certification",
    education: "Bachelor's degree",
    growth: 'Faster than average (7%)',
    onetCode: '29-1031.00',
  },
  {
    title: 'Medical Sonographer',
    description: 'Use special imaging equipment that directs sound waves into a patient\'s body to assess and diagnose medical conditions.',
    avgSalary: '$75,920',
    salaryRange: '$54,000 - $105,000',
    requirements: "Associate's degree in Sonography",
    education: "Associate's degree",
    growth: 'Much faster than average (14%)',
    onetCode: '29-2032.00',
  },
  {
    title: 'Surgical Technologist',
    description: 'Assist in surgical operations. They prepare operating rooms, arrange equipment, and help doctors during surgeries.',
    avgSalary: '$51,510',
    salaryRange: '$37,000 - $73,000',
    requirements: 'Postsecondary certificate',
    education: 'Certificate program',
    growth: 'Average (5%)',
    onetCode: '29-2055.00',
  },
  {
    title: 'Genetic Counselor',
    description: 'Assess individual or family risk for genetic conditions. They provide information and support to help patients make informed decisions.',
    avgSalary: '$85,700',
    salaryRange: '$61,000 - $114,000',
    requirements: "Master's degree in Genetic Counseling",
    education: "Master's degree",
    growth: 'Much faster than average (16%)',
    onetCode: '29-9092.00',
  },

  // Additional Technology Careers
  {
    title: 'DevOps Engineer',
    description: 'Combine software development and IT operations to shorten the development lifecycle and deliver features continuously.',
    avgSalary: '$120,000',
    salaryRange: '$80,000 - $180,000',
    requirements: "Bachelor's degree in Computer Science or related field",
    education: "Bachelor's degree",
    growth: 'Much faster than average (25%)',
    onetCode: '15-1252.00',
  },
  {
    title: 'Cloud Solutions Architect',
    description: 'Design and implement cloud computing strategies for organizations. They work with cloud technologies like AWS, Azure, and Google Cloud.',
    avgSalary: '$128,000',
    salaryRange: '$90,000 - $200,000',
    requirements: "Bachelor's degree and cloud certifications",
    education: "Bachelor's degree",
    growth: 'Much faster than average (22%)',
    onetCode: '15-1199.09',
  },
  {
    title: 'Mobile App Developer',
    description: 'Create applications for mobile devices. They design, code, and test mobile apps for iOS and Android platforms.',
    avgSalary: '$107,000',
    salaryRange: '$70,000 - $165,000',
    requirements: "Bachelor's degree in Computer Science or related field",
    education: "Bachelor's degree",
    growth: 'Much faster than average (22%)',
    onetCode: '15-1256.00',
  },
  {
    title: 'AI/Machine Learning Engineer',
    description: 'Design and build artificial intelligence systems and machine learning models to solve complex problems.',
    avgSalary: '$136,000',
    salaryRange: '$95,000 - $200,000+',
    requirements: "Master's degree in Computer Science, AI, or related field",
    education: "Master's degree",
    growth: 'Much faster than average (36%)',
    onetCode: '15-2051.00',
  },
  {
    title: 'Blockchain Developer',
    description: 'Develop and optimize blockchain protocols, design network architecture, and build blockchain-based applications.',
    avgSalary: '$125,000',
    salaryRange: '$85,000 - $200,000',
    requirements: "Bachelor's degree in Computer Science",
    education: "Bachelor's degree",
    growth: 'Much faster than average (28%)',
    onetCode: '15-1252.00',
  },
  {
    title: 'Information Security Analyst',
    description: 'Plan and implement security measures to protect computer networks and systems.',
    avgSalary: '$102,600',
    salaryRange: '$60,000 - $165,000',
    requirements: "Bachelor's degree in Cybersecurity or related field",
    education: "Bachelor's degree",
    growth: 'Much faster than average (32%)',
    onetCode: '15-1212.00',
  },
  {
    title: 'Game Developer',
    description: 'Design and create video games for computers, mobile devices, and game consoles.',
    avgSalary: '$79,000',
    salaryRange: '$50,000 - $140,000',
    requirements: "Bachelor's degree in Game Development or Computer Science",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '15-1255.01',
  },
  {
    title: 'Systems Analyst',
    description: 'Study an organization\'s current computer systems and procedures and design solutions to help the organization operate more efficiently.',
    avgSalary: '$93,730',
    salaryRange: '$58,000 - $147,000',
    requirements: "Bachelor's degree in Computer Science or Information Systems",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '15-1211.00',
  },

  // Additional Education & Training Careers
  {
    title: 'College Professor',
    description: 'Teach courses in their field of specialty at colleges and universities. They conduct research and publish scholarly papers.',
    avgSalary: '$79,640',
    salaryRange: '$45,000 - $150,000',
    requirements: 'Doctoral degree in field of specialty',
    education: 'Doctoral degree',
    growth: 'Faster than average (12%)',
    onetCode: '25-1099.00',
  },
  {
    title: 'Preschool Teacher',
    description: 'Educate and care for children younger than age 5 who have not yet entered kindergarten.',
    avgSalary: '$30,520',
    salaryRange: '$23,000 - $45,000',
    requirements: "Associate's degree in Early Childhood Education",
    education: "Associate's degree",
    growth: 'Average (4%)',
    onetCode: '25-2011.00',
  },
  {
    title: 'ESL Teacher',
    description: 'Teach English to speakers of other languages. They work with students of all ages in various settings.',
    avgSalary: '$56,720',
    salaryRange: '$38,000 - $85,000',
    requirements: "Bachelor's degree and ESL certification",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '25-3021.00',
  },
  {
    title: 'School Principal',
    description: 'Manage all school operations, including daily school activities. They coordinate curriculums, oversee teachers, and provide a safe learning environment.',
    avgSalary: '$98,420',
    salaryRange: '$65,000 - $145,000',
    requirements: "Master's degree in Education Administration",
    education: "Master's degree",
    growth: 'Average (4%)',
    onetCode: '11-9032.00',
  },
  {
    title: 'Education Administrator',
    description: 'Plan, direct, or coordinate research, instructional, student administration, and counseling activities.',
    avgSalary: '$97,500',
    salaryRange: '$60,000 - $155,000',
    requirements: "Master's degree in Education Administration",
    education: "Master's degree",
    growth: 'Faster than average (8%)',
    onetCode: '11-9033.00',
  },
  {
    title: 'Librarian',
    description: 'Help people find information and conduct research. They manage collections of books and other materials.',
    avgSalary: '$60,820',
    salaryRange: '$38,000 - $95,000',
    requirements: "Master's degree in Library Science",
    education: "Master's degree",
    growth: 'Faster than average (6%)',
    onetCode: '25-4021.00',
  },

  // Business & Management
  {
    title: 'Management Consultant',
    description: 'Propose ways to improve an organization\'s efficiency. They advise managers on how to make organizations more profitable.',
    avgSalary: '$93,000',
    salaryRange: '$55,000 - $160,000',
    requirements: "Bachelor's or Master's degree in Business",
    education: "Bachelor's degree",
    growth: 'Much faster than average (14%)',
    onetCode: '13-1111.00',
  },
  {
    title: 'Operations Manager',
    description: 'Plan, direct, or coordinate the operations of businesses. They help plan the use of resources to meet organizational goals.',
    avgSalary: '$105,250',
    salaryRange: '$60,000 - $175,000',
    requirements: "Bachelor's degree in Business or related field",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '11-1021.00',
  },
  {
    title: 'Sales Manager',
    description: 'Direct sales teams. They set sales goals, analyze data, and develop training programs for sales representatives.',
    avgSalary: '$132,290',
    salaryRange: '$65,000 - $208,000+',
    requirements: "Bachelor's degree in Business or related field",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '11-2022.00',
  },
  {
    title: 'Product Manager',
    description: 'Guide the development of products from conception to launch. They work with engineering, design, and marketing teams.',
    avgSalary: '$115,000',
    salaryRange: '$75,000 - $180,000',
    requirements: "Bachelor's degree in Business or related field",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '11-2021.00',
  },
  {
    title: 'Supply Chain Manager',
    description: 'Coordinate and oversee the entire supply chain operations including purchasing, inventory, and distribution.',
    avgSalary: '$86,000',
    salaryRange: '$55,000 - $140,000',
    requirements: "Bachelor's degree in Supply Chain Management or Business",
    education: "Bachelor's degree",
    growth: 'Much faster than average (28%)',
    onetCode: '11-3071.00',
  },
  {
    title: 'Actuary',
    description: 'Analyze the financial costs of risk and uncertainty. They use mathematics, statistics, and financial theory.',
    avgSalary: '$108,350',
    salaryRange: '$65,000 - $193,000',
    requirements: "Bachelor's degree in Actuarial Science or Mathematics",
    education: "Bachelor's degree",
    growth: 'Much faster than average (24%)',
    onetCode: '15-2011.00',
  },
  {
    title: 'Investment Banker',
    description: 'Help companies and governments raise money by issuing and selling securities. They also provide advice on mergers and acquisitions.',
    avgSalary: '$150,000',
    salaryRange: '$85,000 - $300,000+',
    requirements: "Bachelor's degree in Finance or Economics",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '13-2099.00',
  },
  {
    title: 'Budget Analyst',
    description: 'Help public and private organizations plan their finances. They prepare budget reports and monitor spending.',
    avgSalary: '$79,940',
    salaryRange: '$52,000 - $118,000',
    requirements: "Bachelor's degree in Accounting, Finance, or related field",
    education: "Bachelor's degree",
    growth: 'Average (3%)',
    onetCode: '13-2031.00',
  },

  // Creative & Media
  {
    title: 'Animator',
    description: 'Create animation and visual effects for television, movies, video games, and other media.',
    avgSalary: '$77,700',
    salaryRange: '$45,000 - $125,000',
    requirements: "Bachelor's degree in Animation or related field",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '27-1014.00',
  },
  {
    title: 'Film Director',
    description: 'Control a film\'s artistic and dramatic aspects and visualize the screenplay while guiding the technical crew and actors.',
    avgSalary: '$76,400',
    salaryRange: '$35,000 - $200,000+',
    requirements: "Bachelor's degree in Film or related field",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '27-2012.00',
  },
  {
    title: 'Photographer',
    description: 'Use their technical expertise, creativity, and composition skills to produce and preserve images.',
    avgSalary: '$38,950',
    salaryRange: '$22,000 - $80,000',
    requirements: 'High school diploma; many have a degree in Photography',
    education: 'High school diploma',
    growth: 'Average (4%)',
    onetCode: '27-4021.00',
  },
  {
    title: 'Public Relations Specialist',
    description: 'Create and maintain a favorable public image for their employer or client. They write press releases and plan media campaigns.',
    avgSalary: '$62,800',
    salaryRange: '$38,000 - $115,000',
    requirements: "Bachelor's degree in Public Relations or Communications",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '27-3031.00',
  },
  {
    title: 'Copywriter',
    description: 'Write clear, compelling copy for ads, publications, and websites. Their goal is to sell products or educate and engage consumers.',
    avgSalary: '$63,000',
    salaryRange: '$38,000 - $110,000',
    requirements: "Bachelor's degree in English, Journalism, or Marketing",
    education: "Bachelor's degree",
    growth: 'Faster than average (9%)',
    onetCode: '27-3043.00',
  },
  {
    title: 'Interior Designer',
    description: 'Make interior spaces functional, safe, and beautiful by determining space requirements and selecting decorative items.',
    avgSalary: '$58,120',
    salaryRange: '$35,000 - $96,000',
    requirements: "Bachelor's degree in Interior Design",
    education: "Bachelor's degree",
    growth: 'Average (4%)',
    onetCode: '27-1025.00',
  },
  {
    title: 'Fashion Designer',
    description: 'Create original clothing, accessories, and footwear. They sketch designs, select fabrics, and oversee production.',
    avgSalary: '$75,810',
    salaryRange: '$38,000 - $130,000',
    requirements: "Bachelor's degree in Fashion Design",
    education: "Bachelor's degree",
    growth: 'Little or no change (0%)',
    onetCode: '27-1022.00',
  },
  {
    title: 'Music Producer',
    description: 'Oversee and manage the sound recording and production of music. They work with artists and engineers to create final recordings.',
    avgSalary: '$55,000',
    salaryRange: '$28,000 - $150,000+',
    requirements: "Bachelor's degree in Music Production or related field",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '27-2041.00',
  },

  // Engineering
  {
    title: 'Aerospace Engineer',
    description: 'Design aircraft, spacecraft, satellites, and missiles. They also test prototypes to make sure they function as designed.',
    avgSalary: '$122,270',
    salaryRange: '$77,000 - $171,000',
    requirements: "Bachelor's degree in Aerospace Engineering",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '17-2011.00',
  },
  {
    title: 'Petroleum Engineer',
    description: 'Design and develop methods for extracting oil and gas from deposits below the Earth\'s surface.',
    avgSalary: '$137,330',
    salaryRange: '$78,000 - $208,000+',
    requirements: "Bachelor's degree in Petroleum Engineering",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '17-2171.00',
  },
  {
    title: 'Environmental Engineer',
    description: 'Use principles of engineering, soil science, biology, and chemistry to develop solutions to environmental problems.',
    avgSalary: '$92,120',
    salaryRange: '$58,000 - $142,000',
    requirements: "Bachelor's degree in Environmental Engineering",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '17-2081.00',
  },
  {
    title: 'Nuclear Engineer',
    description: 'Research and develop processes, instruments, and systems used to derive benefits from nuclear energy and radiation.',
    avgSalary: '$116,140',
    salaryRange: '$75,000 - $169,000',
    requirements: "Bachelor's degree in Nuclear Engineering",
    education: "Bachelor's degree",
    growth: 'Decline (-13%)',
    onetCode: '17-2161.00',
  },
  {
    title: 'Industrial Engineer',
    description: 'Find ways to eliminate wastefulness in production processes. They devise efficient systems that integrate workers, machines, and information.',
    avgSalary: '$88,950',
    salaryRange: '$60,000 - $129,000',
    requirements: "Bachelor's degree in Industrial Engineering",
    education: "Bachelor's degree",
    growth: 'Faster than average (10%)',
    onetCode: '17-2112.00',
  },
  {
    title: 'Materials Engineer',
    description: 'Develop, process, and test materials used to create products. They work with metals, ceramics, plastics, and composites.',
    avgSalary: '$95,640',
    salaryRange: '$61,000 - $147,000',
    requirements: "Bachelor's degree in Materials Engineering",
    education: "Bachelor's degree",
    growth: 'Faster than average (8%)',
    onetCode: '17-2131.00',
  },

  // Science & Research
  {
    title: 'Microbiologist',
    description: 'Study microorganisms such as bacteria, viruses, algae, fungi, and parasites to understand how they live, grow, and interact.',
    avgSalary: '$79,260',
    salaryRange: '$48,000 - $133,000',
    requirements: "Bachelor's degree; Ph.D. for research positions",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '19-1022.00',
  },
  {
    title: 'Chemist',
    description: 'Study the composition, structure, and properties of substances. They may develop new products or improve existing ones.',
    avgSalary: '$79,430',
    salaryRange: '$49,000 - $130,000',
    requirements: "Bachelor's degree in Chemistry",
    education: "Bachelor's degree",
    growth: 'Faster than average (6%)',
    onetCode: '19-2031.00',
  },
  {
    title: 'Physicist',
    description: 'Study the ways in which various forms of matter and energy interact. They develop theories and laws based on observation.',
    avgSalary: '$129,850',
    salaryRange: '$64,000 - $208,000+',
    requirements: "Doctoral degree for most research positions",
    education: 'Doctoral degree',
    growth: 'Faster than average (8%)',
    onetCode: '19-2012.00',
  },
  {
    title: 'Astronomer',
    description: 'Study celestial objects such as planets, stars, and galaxies. They use ground-based equipment and space-based telescopes.',
    avgSalary: '$128,160',
    salaryRange: '$62,000 - $189,000',
    requirements: 'Doctoral degree in Astronomy or Physics',
    education: 'Doctoral degree',
    growth: 'Faster than average (8%)',
    onetCode: '19-2011.00',
  },
  {
    title: 'Geologist',
    description: 'Study the physical aspects of the Earth, such as its composition, structure, and processes, to learn about its past, present, and future.',
    avgSalary: '$83,680',
    salaryRange: '$51,000 - $134,000',
    requirements: "Bachelor's degree in Geology",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '19-2042.00',
  },
  {
    title: 'Meteorologist',
    description: 'Study the atmosphere and weather. They use their knowledge to forecast the weather and study climate patterns.',
    avgSalary: '$99,740',
    salaryRange: '$51,000 - $151,000',
    requirements: "Bachelor's degree in Meteorology or Atmospheric Science",
    education: "Bachelor's degree",
    growth: 'Faster than average (6%)',
    onetCode: '19-2021.00',
  },
  {
    title: 'Forensic Scientist',
    description: 'Collect, identify, classify, and analyze physical evidence related to criminal investigations.',
    avgSalary: '$61,930',
    salaryRange: '$40,000 - $100,000',
    requirements: "Bachelor's degree in Forensic Science or Natural Science",
    education: "Bachelor's degree",
    growth: 'Much faster than average (14%)',
    onetCode: '19-4092.00',
  },
  {
    title: 'Marine Biologist',
    description: 'Study marine organisms and their behaviors and interactions with the environment.',
    avgSalary: '$66,350',
    salaryRange: '$42,000 - $108,000',
    requirements: "Bachelor's degree; Master's or Ph.D. for research",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '19-1029.00',
  },

  // Legal & Public Service
  {
    title: 'Judge',
    description: 'Preside over legal proceedings in courts. They apply the law and oversee the legal process in courts.',
    avgSalary: '$133,920',
    salaryRange: '$70,000 - $208,000+',
    requirements: 'Law degree and years of legal experience',
    education: 'Doctoral degree',
    growth: 'Average (2%)',
    onetCode: '23-1023.00',
  },
  {
    title: 'Court Reporter',
    description: 'Create verbatim transcripts of speeches, conversations, and legal proceedings.',
    avgSalary: '$60,380',
    salaryRange: '$32,000 - $105,000',
    requirements: 'Postsecondary certificate',
    education: 'Certificate program',
    growth: 'Average (3%)',
    onetCode: '23-2091.00',
  },
  {
    title: 'FBI Agent',
    description: 'Investigate violations of federal law. They protect national security and uphold the law.',
    avgSalary: '$78,000',
    salaryRange: '$52,000 - $130,000',
    requirements: "Bachelor's degree and FBI training",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '33-3021.00',
  },
  {
    title: 'Firefighter',
    description: 'Protect the public by responding to fires and other emergencies. They are often the first responders.',
    avgSalary: '$52,500',
    salaryRange: '$28,000 - $93,000',
    requirements: 'High school diploma and fire academy training',
    education: 'High school diploma',
    growth: 'Faster than average (8%)',
    onetCode: '33-2011.00',
  },
  {
    title: 'Emergency Medical Technician (EMT)',
    description: 'Provide emergency medical care to critically ill or injured patients. They transport patients to medical facilities.',
    avgSalary: '$36,650',
    salaryRange: '$25,000 - $60,000',
    requirements: 'Postsecondary certificate',
    education: 'Certificate program',
    growth: 'Faster than average (7%)',
    onetCode: '29-2042.00',
  },
  {
    title: 'Urban and Regional Planner',
    description: 'Develop plans for the use of land and physical facilities of communities and metropolitan areas.',
    avgSalary: '$78,500',
    salaryRange: '$48,000 - $121,000',
    requirements: "Master's degree in Urban Planning",
    education: "Master's degree",
    growth: 'Faster than average (7%)',
    onetCode: '19-3051.00',
  },

  // Trades & Technical
  {
    title: 'Carpenter',
    description: 'Construct, repair, and install building frameworks and structures made from wood and other materials.',
    avgSalary: '$48,260',
    salaryRange: '$31,000 - $84,000',
    requirements: 'High school diploma and apprenticeship',
    education: 'High school diploma',
    growth: 'Average (2%)',
    onetCode: '47-2031.00',
  },
  {
    title: 'Welder',
    description: 'Use hand-held or remotely controlled equipment to join or cut metal parts.',
    avgSalary: '$45,190',
    salaryRange: '$30,000 - $66,000',
    requirements: 'High school diploma and technical training',
    education: 'High school diploma',
    growth: 'Average (3%)',
    onetCode: '51-4121.00',
  },
  {
    title: 'Auto Mechanic',
    description: 'Inspect, maintain, and repair cars and light trucks.',
    avgSalary: '$46,880',
    salaryRange: '$28,000 - $75,000',
    requirements: 'Postsecondary training',
    education: 'Certificate program',
    growth: 'Little or no change (1%)',
    onetCode: '49-3023.00',
  },
  {
    title: 'Wind Turbine Technician',
    description: 'Install, maintain, and repair wind turbines. They diagnose problems and make repairs.',
    avgSalary: '$56,260',
    salaryRange: '$38,000 - $81,000',
    requirements: 'Technical training or associate degree',
    education: 'Certificate program',
    growth: 'Much faster than average (68%)',
    onetCode: '49-9081.00',
  },
  {
    title: 'Solar Photovoltaic Installer',
    description: 'Assemble, install, and maintain solar panel systems on rooftops or other structures.',
    avgSalary: '$47,670',
    salaryRange: '$33,000 - $63,000',
    requirements: 'High school diploma and on-the-job training',
    education: 'High school diploma',
    growth: 'Much faster than average (52%)',
    onetCode: '47-2231.00',
  },
  {
    title: 'Aircraft Mechanic',
    description: 'Diagnose mechanical or electrical problems, repair wings, brakes, and other parts, and perform scheduled maintenance.',
    avgSalary: '$65,550',
    salaryRange: '$42,000 - $96,000',
    requirements: 'FAA certification',
    education: 'Certificate program',
    growth: 'Faster than average (6%)',
    onetCode: '49-3011.00',
  },

  // Additional Diverse Careers
  {
    title: 'Athletic Trainer',
    description: 'Specialize in preventing, diagnosing, and treating muscle and bone injuries. They work with athletes and active individuals.',
    avgSalary: '$48,440',
    salaryRange: '$32,000 - $75,000',
    requirements: "Master's degree in Athletic Training",
    education: "Master's degree",
    growth: 'Much faster than average (17%)',
    onetCode: '29-9091.00',
  },
  {
    title: 'Fitness Trainer',
    description: 'Lead, instruct, and motivate individuals or groups in exercise activities. They demonstrate proper techniques.',
    avgSalary: '$40,700',
    salaryRange: '$21,000 - $76,000',
    requirements: 'High school diploma and certification',
    education: 'High school diploma',
    growth: 'Much faster than average (19%)',
    onetCode: '39-9031.00',
  },
  {
    title: 'Massage Therapist',
    description: 'Treat clients by using touch to manipulate muscles and other soft tissues of the body.',
    avgSalary: '$43,620',
    salaryRange: '$23,000 - $77,000',
    requirements: 'Postsecondary education and state license',
    education: 'Certificate program',
    growth: 'Much faster than average (20%)',
    onetCode: '31-9011.00',
  },
  {
    title: 'Translator',
    description: 'Convert information from one language into another. They work with written text.',
    avgSalary: '$52,330',
    salaryRange: '$30,000 - $94,000',
    requirements: "Bachelor's degree and fluency in two or more languages",
    education: "Bachelor's degree",
    growth: 'Much faster than average (24%)',
    onetCode: '27-3091.00',
  },
  {
    title: 'Interpreter',
    description: 'Convert information from one spoken language into another. They work with live conversations.',
    avgSalary: '$52,330',
    salaryRange: '$30,000 - $94,000',
    requirements: "Bachelor's degree and fluency in two or more languages",
    education: "Bachelor's degree",
    growth: 'Much faster than average (24%)',
    onetCode: '27-3091.00',
  },
  {
    title: 'Flight Attendant',
    description: 'Provide routine services and respond to emergencies to ensure the safety and comfort of airline passengers.',
    avgSalary: '$61,640',
    salaryRange: '$30,000 - $80,000',
    requirements: 'High school diploma and airline training',
    education: 'High school diploma',
    growth: 'Much faster than average (21%)',
    onetCode: '53-2031.00',
  },
  {
    title: 'Air Traffic Controller',
    description: 'Coordinate the movement of aircraft to maintain safe distances between them.',
    avgSalary: '$130,420',
    salaryRange: '$72,000 - $184,000',
    requirements: "Associate's or Bachelor's degree and FAA training",
    education: "Associate's degree",
    growth: 'Average (4%)',
    onetCode: '53-2021.00',
  },
  {
    title: 'Landscape Architect',
    description: 'Design outdoor areas, landmarks, and structures to achieve environmental, social-behavioral, or aesthetic outcomes.',
    avgSalary: '$70,630',
    salaryRange: '$45,000 - $112,000',
    requirements: "Bachelor's or Master's degree in Landscape Architecture",
    education: "Bachelor's degree",
    growth: 'Average (5%)',
    onetCode: '17-1012.00',
  },
  {
    title: 'Curator',
    description: 'Oversee collections of artwork and historic items, and may conduct public service activities for an institution.',
    avgSalary: '$60,110',
    salaryRange: '$30,000 - $112,000',
    requirements: "Master's degree in Art History, Museum Studies, or related field",
    education: "Master's degree",
    growth: 'Much faster than average (19%)',
    onetCode: '25-4012.00',
  },
  {
    title: 'Epidemiologist',
    description: 'Investigate patterns and causes of disease and injury in humans. They seek to reduce the risk and occurrence of negative health outcomes.',
    avgSalary: '$74,560',
    salaryRange: '$48,000 - $119,000',
    requirements: "Master's degree in Public Health",
    education: "Master's degree",
    growth: 'Much faster than average (26%)',
    onetCode: '19-1041.00',
  },
];

async function seedMoreCareers() {
  console.log('🌱 Adding 100+ additional careers to database...\n');

  let savedCount = 0;
  let skippedCount = 0;

  for (const career of additionalCareers) {
    try {
      const existing = await prisma.career.findFirst({
        where: { title: career.title },
      });

      if (!existing) {
        await prisma.career.create({
          data: {
            ...career,
            dayInLife: career.description,
            dayInLifeList: [],
          },
        });
        console.log(`✓ Added: ${career.title}`);
        savedCount++;
      } else {
        console.log(`- Skipped: ${career.title}`);
        skippedCount++;
      }
    } catch (error) {
      console.error(`Error saving ${career.title}:`, error);
    }
  }

  console.log('\n✅ Additional careers seeding completed!');
  console.log(`📊 Careers saved: ${savedCount}`);
  console.log(`⏭️  Duplicates skipped: ${skippedCount}`);

  const totalCareers = await prisma.career.count();
  console.log(`💾 Total careers in database: ${totalCareers}\n`);
}

seedMoreCareers()
  .catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
