import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Adding 50 more careers to database...\n');

  const careers = [
    // Healthcare & Medical
    {
      title: 'Genetic Counselor',
      description: 'Assess individual or family risk for genetic conditions, provide counseling and support, and interpret genetic test results.',
      avgSalary: '$85,700',
      salaryRange: '$61,000 - $114,000',
      requirements: "Master's degree in Genetic Counseling, certification by American Board of Genetic Counseling",
      education: "Master's degree",
      growth: 'Much faster than average (16%)',
      dayInLife: 'Meet with patients to discuss family medical history, explain genetic testing options, interpret test results, and provide emotional support.',
      dayInLifeList: [
        'Review patient family medical histories',
        'Explain genetic testing procedures and implications',
        'Interpret genetic test results',
        'Provide counseling on genetic conditions',
        'Coordinate with physicians and specialists',
        'Document patient consultations',
      ],
      onetCode: '29-9092.00',
    },
    {
      title: 'Perfusionist',
      description: 'Operate heart-lung machines and other artificial life support equipment during medical procedures that require circulatory or respiratory support.',
      avgSalary: '$126,000',
      salaryRange: '$87,000 - $165,000',
      requirements: "Bachelor's degree in perfusion technology, certification by American Board of Cardiovascular Perfusion",
      education: "Bachelor's degree",
      growth: 'Faster than average (8%)',
      dayInLife: 'Prepare and operate cardiopulmonary bypass equipment during cardiac surgeries, monitor patient vital signs, and manage blood flow.',
      dayInLifeList: [
        'Set up heart-lung machines before surgery',
        'Monitor patient circulation during procedures',
        'Adjust equipment settings in real-time',
        'Manage blood flow and oxygenation',
        'Maintain sterile equipment',
        'Document perfusion records',
      ],
      onetCode: '29-2036.00',
    },
    {
      title: 'Nurse Midwife',
      description: 'Provide prenatal care, deliver babies, and offer postpartum care to mothers and newborns in various healthcare settings.',
      avgSalary: '$112,830',
      salaryRange: '$81,000 - $152,000',
      requirements: "Master's degree in Nurse-Midwifery, RN license, certification by American Midwifery Certification Board",
      education: "Master's degree",
      growth: 'Much faster than average (40%)',
      dayInLife: 'Conduct prenatal exams, monitor labor and delivery, perform deliveries, and provide postpartum care and newborn assessments.',
      dayInLifeList: [
        'Conduct prenatal checkups and ultrasounds',
        'Monitor fetal development',
        'Attend and manage labor and delivery',
        'Perform postpartum examinations',
        'Provide family planning counseling',
        'Educate expectant mothers',
      ],
      onetCode: '29-1161.00',
    },
    {
      title: 'Prosthodontist',
      description: 'Specialize in replacing missing teeth and restoring oral function through dentures, bridges, implants, and other prosthetic devices.',
      avgSalary: '$208,000',
      salaryRange: '$126,000 - $300,000+',
      requirements: 'Doctor of Dental Surgery (DDS) or Doctor of Dental Medicine (DMD), 3-year prosthodontics residency, specialty certification',
      education: 'Doctoral degree + specialty training',
      growth: 'Average (4%)',
      dayInLife: 'Design and fit dental prosthetics, perform complex restorative procedures, and collaborate with dental labs on custom solutions.',
      dayInLifeList: [
        'Examine patients needing tooth replacement',
        'Design custom dental prosthetics',
        'Fit and adjust dentures and implants',
        'Perform maxillofacial prosthetic procedures',
        'Collaborate with dental laboratories',
        'Follow up on prosthetic adjustments',
      ],
      onetCode: '29-1024.00',
    },

    // Technology & Engineering
    {
      title: 'Blockchain Developer',
      description: 'Design and implement blockchain protocols, develop smart contracts, and create decentralized applications (dApps).',
      avgSalary: '$146,000',
      salaryRange: '$98,000 - $200,000+',
      requirements: "Bachelor's degree in Computer Science, expertise in blockchain platforms (Ethereum, Solidity, Web3), cryptography knowledge",
      education: "Bachelor's degree",
      growth: 'Much faster than average (23%)',
      dayInLife: 'Develop smart contracts, implement blockchain solutions, test decentralized applications, and ensure security of blockchain systems.',
      dayInLifeList: [
        'Write and deploy smart contracts',
        'Design blockchain architecture',
        'Implement consensus mechanisms',
        'Test and audit blockchain code',
        'Optimize transaction processing',
        'Research emerging blockchain technologies',
      ],
      onetCode: '15-1252.00',
    },
    {
      title: 'Site Reliability Engineer (SRE)',
      description: 'Ensure the reliability, availability, and performance of large-scale systems by combining software engineering with IT operations.',
      avgSalary: '$140,000',
      salaryRange: '$105,000 - $190,000',
      requirements: "Bachelor's degree in Computer Science, expertise in distributed systems, automation, and monitoring tools",
      education: "Bachelor's degree",
      growth: 'Much faster than average (22%)',
      dayInLife: 'Monitor system performance, automate operations tasks, respond to incidents, and improve system reliability through engineering solutions.',
      dayInLifeList: [
        'Monitor system health and performance metrics',
        'Automate deployment and scaling processes',
        'Respond to and resolve production incidents',
        'Conduct postmortem analyses',
        'Implement reliability improvements',
        'Collaborate with development teams on SLOs',
      ],
      onetCode: '15-1252.00',
    },
    {
      title: 'Embedded Systems Engineer',
      description: 'Design and develop software for embedded systems in devices like medical equipment, automotive systems, and IoT devices.',
      avgSalary: '$112,000',
      salaryRange: '$82,000 - $155,000',
      requirements: "Bachelor's degree in Computer Engineering or Electrical Engineering, expertise in C/C++, RTOS, and microcontrollers",
      education: "Bachelor's degree",
      growth: 'Faster than average (7%)',
      dayInLife: 'Develop firmware for embedded devices, test hardware-software integration, and optimize performance for resource-constrained systems.',
      dayInLifeList: [
        'Write firmware in C/C++',
        'Test embedded software on hardware',
        'Debug hardware-software interfaces',
        'Optimize code for memory and power',
        'Collaborate with hardware engineers',
        'Document technical specifications',
      ],
      onetCode: '15-1252.00',
    },
    {
      title: 'Quantum Computing Researcher',
      description: 'Research and develop quantum algorithms, quantum hardware, and applications for quantum computing systems.',
      avgSalary: '$158,000',
      salaryRange: '$110,000 - $220,000+',
      requirements: 'Ph.D. in Physics, Computer Science, or related field, expertise in quantum mechanics and quantum algorithms',
      education: 'Doctoral degree',
      growth: 'Much faster than average (emerging field)',
      dayInLife: 'Develop quantum algorithms, conduct research on quantum systems, collaborate with physicists, and publish research findings.',
      dayInLifeList: [
        'Design quantum algorithms',
        'Conduct quantum computing experiments',
        'Analyze quantum system performance',
        'Collaborate with research teams',
        'Publish research papers',
        'Present findings at conferences',
      ],
      onetCode: '19-1022.00',
    },
    {
      title: 'Network Security Engineer',
      description: 'Design, implement, and maintain security measures to protect computer networks from cyber threats and unauthorized access.',
      avgSalary: '$120,000',
      salaryRange: '$88,000 - $165,000',
      requirements: "Bachelor's degree in Cybersecurity or Computer Science, certifications like CISSP, CEH, or CCNA Security",
      education: "Bachelor's degree",
      growth: 'Much faster than average (33%)',
      dayInLife: 'Monitor network traffic for threats, implement firewalls and intrusion detection systems, conduct security audits, and respond to breaches.',
      dayInLifeList: [
        'Monitor network security alerts',
        'Configure firewalls and VPNs',
        'Conduct vulnerability assessments',
        'Implement security patches',
        'Investigate security incidents',
        'Develop security policies',
      ],
      onetCode: '15-1212.00',
    },

    // Business & Finance
    {
      title: 'Actuary',
      description: 'Analyze financial risks using mathematics, statistics, and financial theory to help businesses develop policies that minimize risk.',
      avgSalary: '$108,350',
      salaryRange: '$68,000 - $193,000',
      requirements: "Bachelor's degree in Actuarial Science, Mathematics, or Statistics, professional actuarial certifications (SOA or CAS)",
      education: "Bachelor's degree + certifications",
      growth: 'Faster than average (24%)',
      dayInLife: 'Analyze statistical data, develop probability models, calculate insurance premiums and pension plans, and assess financial risks.',
      dayInLifeList: [
        'Analyze mortality and morbidity data',
        'Develop financial risk models',
        'Calculate insurance premiums',
        'Prepare actuarial reports',
        'Advise on pension fund management',
        'Study for actuarial exams',
      ],
      onetCode: '15-2011.00',
    },
    {
      title: 'Investment Banker',
      description: 'Help companies and governments raise capital, facilitate mergers and acquisitions, and provide financial advisory services.',
      avgSalary: '$165,000',
      salaryRange: '$100,000 - $300,000+',
      requirements: "Bachelor's degree in Finance, Economics, or Business, MBA often preferred, Series 79 and 63 licenses",
      education: "Bachelor's degree (MBA preferred)",
      growth: 'Average (4%)',
      dayInLife: 'Analyze financial data, create pitch books, negotiate deals, coordinate due diligence, and manage client relationships.',
      dayInLifeList: [
        'Conduct financial analysis and modeling',
        'Prepare pitch books for clients',
        'Negotiate merger and acquisition deals',
        'Coordinate due diligence processes',
        'Present investment opportunities',
        'Build client relationships',
      ],
      onetCode: '13-2099.01',
    },
    {
      title: 'Compliance Officer',
      description: 'Ensure organizations comply with regulatory requirements, internal policies, and industry standards across various sectors.',
      avgSalary: '$75,800',
      salaryRange: '$51,000 - $122,000',
      requirements: "Bachelor's degree in Business, Finance, or related field, certifications like CRCM or CCEP often preferred",
      education: "Bachelor's degree",
      growth: 'Faster than average (6%)',
      dayInLife: 'Review company policies, conduct compliance audits, investigate violations, provide training, and ensure regulatory adherence.',
      dayInLifeList: [
        'Monitor regulatory changes',
        'Conduct compliance audits',
        'Investigate compliance violations',
        'Develop compliance training programs',
        'Review and update policies',
        'Report to regulatory agencies',
      ],
      onetCode: '13-1041.01',
    },
    {
      title: 'Venture Capitalist',
      description: 'Evaluate and invest in startup companies and emerging businesses with high growth potential in exchange for equity.',
      avgSalary: '$155,000',
      salaryRange: '$95,000 - $350,000+',
      requirements: "Bachelor's degree in Finance or Business, MBA preferred, extensive business and investment experience",
      education: "Bachelor's degree (MBA highly preferred)",
      growth: 'Average (5%)',
      dayInLife: 'Evaluate business plans, conduct due diligence, negotiate investment terms, mentor portfolio companies, and manage investments.',
      dayInLifeList: [
        'Review startup pitch decks',
        'Conduct market research and due diligence',
        'Negotiate investment terms',
        'Attend board meetings of portfolio companies',
        'Provide strategic guidance to founders',
        'Network at industry events',
      ],
      onetCode: '13-2099.00',
    },

    // Creative & Media
    {
      title: 'Foley Artist',
      description: 'Create and record custom sound effects for films, television, and video games to enhance audio production.',
      avgSalary: '$58,000',
      salaryRange: '$35,000 - $95,000',
      requirements: 'Audio production training, expertise in sound recording and manipulation, creative sound design skills',
      education: "Associate's or Bachelor's degree in Audio Production",
      growth: 'Average (5%)',
      dayInLife: 'Watch video footage, create sound effects using various props, record sounds in sync with visual media, and collaborate with sound editors.',
      dayInLifeList: [
        'Watch film scenes to identify needed sounds',
        'Create sound effects using props and objects',
        'Record sounds in sync with video',
        'Experiment with different materials for sounds',
        'Edit and refine recorded audio',
        'Collaborate with sound designers and editors',
      ],
      onetCode: '27-4014.00',
    },
    {
      title: 'Lighting Designer',
      description: 'Design and implement lighting plans for theater productions, concerts, architectural spaces, and events.',
      avgSalary: '$72,000',
      salaryRange: '$45,000 - $115,000',
      requirements: "Bachelor's degree in Theater, Lighting Design, or related field, expertise in lighting equipment and design software",
      education: "Bachelor's degree",
      growth: 'Faster than average (6%)',
      dayInLife: 'Develop lighting concepts, create lighting plots, program lighting consoles, collaborate with directors, and oversee technical rehearsals.',
      dayInLifeList: [
        'Read scripts and meet with directors',
        'Create lighting plots and cue sheets',
        'Program lighting consoles',
        'Supervise lighting installation',
        'Attend technical and dress rehearsals',
        'Adjust lighting based on feedback',
      ],
      onetCode: '27-1029.00',
    },
    {
      title: 'Broadcast Engineer',
      description: 'Install, maintain, and operate equipment for radio and television broadcasts, ensuring signal quality and technical reliability.',
      avgSalary: '$73,000',
      salaryRange: '$48,000 - $115,000',
      requirements: "Bachelor's degree in Broadcast Engineering or related field, FCC General Radiotelephone Operator License may be required",
      education: "Bachelor's degree",
      growth: 'Decline (-10%)',
      dayInLife: 'Monitor broadcast signals, maintain transmitters and studio equipment, troubleshoot technical issues, and ensure compliance with FCC regulations.',
      dayInLifeList: [
        'Monitor broadcast signal quality',
        'Maintain studio and transmission equipment',
        'Troubleshoot technical problems',
        'Install new broadcast equipment',
        'Ensure FCC compliance',
        'Test and calibrate equipment',
      ],
      onetCode: '17-3011.00',
    },
    {
      title: 'Comic Book Artist',
      description: 'Create visual narratives for comic books and graphic novels through sequential art, character design, and storytelling.',
      avgSalary: '$52,000',
      salaryRange: '$30,000 - $95,000',
      requirements: 'Portfolio demonstrating sequential art skills, may have degree in Fine Arts or Illustration, digital art proficiency',
      education: 'Variable (portfolio-based)',
      growth: 'Average (4%)',
      dayInLife: 'Read scripts, sketch character designs and layouts, create detailed pencil artwork, ink pages, and collaborate with writers and colorists.',
      dayInLifeList: [
        'Read and interpret comic scripts',
        'Create character and scene layouts',
        'Pencil detailed artwork',
        'Ink final line art',
        'Collaborate with writers and editors',
        'Meet publishing deadlines',
      ],
      onetCode: '27-1013.00',
    },

    // Science & Research
    {
      title: 'Oceanographer',
      description: 'Study physical, chemical, and biological aspects of the ocean, including marine life, ocean currents, and seafloor geology.',
      avgSalary: '$96,000',
      salaryRange: '$56,000 - $155,000',
      requirements: "Bachelor's degree in Oceanography or Marine Science, Master's or Ph.D. for research positions",
      education: "Bachelor's degree (advanced degree preferred)",
      growth: 'Average (5%)',
      dayInLife: 'Conduct ocean research expeditions, collect water and sediment samples, analyze oceanographic data, and publish research findings.',
      dayInLifeList: [
        'Plan and conduct research expeditions',
        'Collect ocean water and sediment samples',
        'Operate oceanographic instruments',
        'Analyze data on ocean conditions',
        'Write research papers and reports',
        'Present findings at conferences',
      ],
      onetCode: '19-2042.00',
    },
    {
      title: 'Forensic Scientist',
      description: 'Analyze physical evidence from crime scenes using scientific methods to support criminal investigations and legal proceedings.',
      avgSalary: '$64,250',
      salaryRange: '$42,000 - $105,000',
      requirements: "Bachelor's degree in Forensic Science, Chemistry, or Biology, specialized training in forensic techniques",
      education: "Bachelor's degree",
      growth: 'Much faster than average (13%)',
      dayInLife: 'Examine evidence from crime scenes, conduct laboratory tests, document findings, prepare reports, and testify in court.',
      dayInLifeList: [
        'Analyze physical evidence (DNA, fingerprints, fibers)',
        'Conduct laboratory tests',
        'Document findings and chain of custody',
        'Prepare detailed forensic reports',
        'Testify as expert witness in court',
        'Maintain laboratory equipment',
      ],
      onetCode: '19-4092.00',
    },
    {
      title: 'Volcanologist',
      description: 'Study volcanoes, volcanic activity, and related geological phenomena to understand eruption patterns and predict volcanic events.',
      avgSalary: '$87,000',
      salaryRange: '$55,000 - $135,000',
      requirements: "Bachelor's degree in Geology or Geophysics, Master's or Ph.D. for research positions, fieldwork experience",
      education: "Bachelor's degree (advanced degree preferred)",
      growth: 'Average (5%)',
      dayInLife: 'Monitor volcanic activity, collect lava and gas samples, analyze seismic data, conduct fieldwork near active volcanoes, and assess eruption risks.',
      dayInLifeList: [
        'Monitor seismic activity around volcanoes',
        'Collect volcanic rock and gas samples',
        'Conduct fieldwork at volcanic sites',
        'Analyze volcanic hazard data',
        'Develop eruption prediction models',
        'Advise on volcanic risk mitigation',
      ],
      onetCode: '19-2042.00',
    },
    {
      title: 'Astrobiologist',
      description: 'Study the possibility of life beyond Earth, examining extreme environments and searching for biosignatures in space.',
      avgSalary: '$104,000',
      salaryRange: '$65,000 - $165,000',
      requirements: "Ph.D. in Astrobiology, Biology, Astronomy, or related field, research experience in extremophiles or planetary science",
      education: 'Doctoral degree',
      growth: 'Average (emerging field)',
      dayInLife: 'Research extremophile organisms, analyze data from space missions, study planetary atmospheres, and search for signs of extraterrestrial life.',
      dayInLifeList: [
        'Study extremophile organisms on Earth',
        'Analyze data from Mars rovers and space probes',
        'Research planetary atmospheres',
        'Search for biosignatures in exoplanets',
        'Conduct laboratory experiments',
        'Publish astrobiology research',
      ],
      onetCode: '19-1029.00',
    },

    // Education & Social Services
    {
      title: 'Instructional Designer',
      description: 'Design and develop educational courses, training programs, and learning experiences using instructional theory and technology.',
      avgSalary: '$68,000',
      salaryRange: '$48,000 - $98,000',
      requirements: "Bachelor's or Master's degree in Instructional Design, Education, or related field, expertise in learning management systems",
      education: "Bachelor's or Master's degree",
      growth: 'Faster than average (6%)',
      dayInLife: 'Analyze learning needs, design course curricula, develop educational materials, implement e-learning technologies, and evaluate program effectiveness.',
      dayInLifeList: [
        'Conduct needs assessments for learning programs',
        'Design course curricula and learning objectives',
        'Develop instructional materials and multimedia',
        'Create e-learning modules',
        'Test and refine learning programs',
        'Evaluate training effectiveness',
      ],
      onetCode: '25-9031.00',
    },
    {
      title: 'School Psychologist',
      description: 'Support students mental health and learning by providing psychological assessments, counseling, and interventions in educational settings.',
      avgSalary: '$81,500',
      salaryRange: '$57,000 - $119,000',
      requirements: "Specialist degree (Ed.S.) or Doctoral degree in School Psychology, state certification or licensure",
      education: 'Specialist or Doctoral degree',
      growth: 'Faster than average (8%)',
      dayInLife: 'Assess students with learning difficulties, provide counseling, develop intervention plans, consult with teachers and parents, and support crisis response.',
      dayInLifeList: [
        'Conduct psychological and educational assessments',
        'Provide individual and group counseling',
        'Develop behavioral intervention plans',
        'Consult with teachers and administrators',
        'Support students in crisis',
        'Participate in IEP meetings',
      ],
      onetCode: '19-3034.00',
    },
    {
      title: 'Adult Education Teacher',
      description: 'Teach academic, vocational, and life skills to adult learners in various settings including community colleges and learning centers.',
      avgSalary: '$57,000',
      salaryRange: '$37,000 - $89,000',
      requirements: "Bachelor's degree minimum, Master's degree preferred, teaching certification may be required depending on subject",
      education: "Bachelor's degree (Master's preferred)",
      growth: 'Average (6%)',
      dayInLife: 'Develop lesson plans for adult learners, teach classes in various subjects, assess student progress, and adapt teaching methods to diverse needs.',
      dayInLifeList: [
        'Plan lessons for adult education courses',
        'Teach GED, ESL, or vocational classes',
        'Assess adult learner progress',
        'Adapt teaching to different learning styles',
        'Provide career counseling',
        'Maintain student records',
      ],
      onetCode: '25-3011.00',
    },

    // Legal & Public Policy
    {
      title: 'Immigration Lawyer',
      description: 'Advise and represent clients on immigration matters including visas, citizenship, deportation, and asylum cases.',
      avgSalary: '$126,000',
      salaryRange: '$75,000 - $200,000+',
      requirements: 'Juris Doctor (J.D.) degree, state bar admission, expertise in immigration law',
      education: 'Doctoral degree (J.D.)',
      growth: 'Average (8%)',
      dayInLife: 'Meet with clients, prepare visa applications, represent clients in immigration court, file appeals, and stay current on immigration policy.',
      dayInLifeList: [
        'Consult with clients on immigration options',
        'Prepare and file visa applications',
        'Represent clients in immigration court',
        'File appeals and motions',
        'Research immigration law changes',
        'Communicate with USCIS',
      ],
      onetCode: '23-1011.00',
    },
    {
      title: 'Legislative Analyst',
      description: 'Research and analyze proposed legislation, assess policy impacts, and provide recommendations to lawmakers and government agencies.',
      avgSalary: '$77,000',
      salaryRange: '$52,000 - $115,000',
      requirements: "Bachelor's degree in Public Policy, Political Science, or related field, Master's degree often preferred",
      education: "Bachelor's degree (Master's preferred)",
      growth: 'Average (5%)',
      dayInLife: 'Research policy issues, analyze legislation, write policy briefs, assess fiscal impacts, and brief legislators on policy implications.',
      dayInLifeList: [
        'Research proposed legislation',
        'Analyze policy and fiscal impacts',
        'Write policy briefs and reports',
        'Brief legislators and staff',
        'Track bill progress',
        'Attend committee hearings',
      ],
      onetCode: '19-3099.00',
    },
    {
      title: 'Arbitrator',
      description: 'Facilitate dispute resolution between parties outside of court by hearing arguments and making binding or non-binding decisions.',
      avgSalary: '$68,000',
      salaryRange: '$40,000 - $125,000',
      requirements: "Bachelor's degree, often law degree or expertise in specific field, arbitration certification",
      education: "Bachelor's degree (J.D. preferred)",
      growth: 'Faster than average (8%)',
      dayInLife: 'Review case materials, conduct hearings, listen to evidence and arguments, apply relevant laws and rules, and issue arbitration decisions.',
      dayInLifeList: [
        'Review case documents and evidence',
        'Conduct arbitration hearings',
        'Listen to arguments from both parties',
        'Apply relevant laws and contracts',
        'Issue written arbitration decisions',
        'Maintain neutrality and impartiality',
      ],
      onetCode: '23-1022.00',
    },

    // Skilled Trades & Specialized Services
    {
      title: 'Aviation Mechanic',
      description: 'Inspect, maintain, and repair aircraft systems including engines, hydraulics, and electrical systems to ensure flight safety.',
      avgSalary: '$69,000',
      salaryRange: '$47,000 - $99,000',
      requirements: 'FAA Airframe and Powerplant (A&P) certification, completion of FAA-approved training program',
      education: 'Certificate/training program',
      growth: 'Average (6%)',
      dayInLife: 'Inspect aircraft systems, diagnose mechanical problems, perform scheduled maintenance, repair or replace parts, and document all work.',
      dayInLifeList: [
        'Conduct pre-flight inspections',
        'Diagnose mechanical and electrical issues',
        'Perform scheduled maintenance',
        'Repair or replace aircraft components',
        'Test aircraft systems',
        'Document maintenance records',
      ],
      onetCode: '49-3011.00',
    },
    {
      title: 'Wind Turbine Technician',
      description: 'Install, maintain, and repair wind turbines used for renewable energy generation, working at significant heights.',
      avgSalary: '$57,000',
      salaryRange: '$42,000 - $76,000',
      requirements: 'Technical certificate or associate degree in wind energy technology, safety training, ability to work at heights',
      education: "Certificate or Associate's degree",
      growth: 'Much faster than average (44%)',
      dayInLife: 'Climb wind turbines, perform inspections, conduct preventive maintenance, troubleshoot electrical and mechanical issues, and replace components.',
      dayInLifeList: [
        'Climb turbines to access components',
        'Conduct routine inspections',
        'Perform preventive maintenance',
        'Troubleshoot mechanical and electrical issues',
        'Replace worn or damaged parts',
        'Document maintenance activities',
      ],
      onetCode: '49-9081.00',
    },
    {
      title: 'Marine Mechanic',
      description: 'Repair and maintain boats, yachts, and other watercraft including engines, electrical systems, and hull components.',
      avgSalary: '$51,000',
      salaryRange: '$35,000 - $73,000',
      requirements: 'Technical training or apprenticeship, certification from ABYC (American Boat and Yacht Council) preferred',
      education: 'Technical training/certification',
      growth: 'Average (5%)',
      dayInLife: 'Diagnose engine problems, repair or replace marine engines, maintain electrical systems, inspect hulls, and perform seasonal maintenance.',
      dayInLifeList: [
        'Diagnose marine engine issues',
        'Repair or rebuild boat engines',
        'Service electrical and fuel systems',
        'Inspect and repair hull damage',
        'Perform seasonal winterization',
        'Test boats after repairs',
      ],
      onetCode: '49-3051.00',
    },
    {
      title: 'Watchmaker',
      description: 'Repair, restore, and maintain mechanical watches and clocks, including luxury timepieces and antique pieces.',
      avgSalary: '$48,000',
      salaryRange: '$32,000 - $75,000',
      requirements: 'Watchmaking school certification or apprenticeship, AWCI (American Watchmakers-Clockmakers Institute) certification',
      education: 'Specialized training/certification',
      growth: 'Decline (-3%)',
      dayInLife: 'Disassemble watches, clean and lubricate movements, replace worn parts, adjust timing, and restore antique timepieces.',
      dayInLifeList: [
        'Examine watches under magnification',
        'Disassemble watch movements',
        'Clean and lubricate components',
        'Replace worn or broken parts',
        'Adjust timing and accuracy',
        'Reassemble and test watches',
      ],
      onetCode: '49-9064.00',
    },

    // Hospitality & Service
    {
      title: 'Hotel General Manager',
      description: 'Oversee all operations of a hotel including guest services, staff management, budgeting, and maintaining property standards.',
      avgSalary: '$98,000',
      salaryRange: '$62,000 - $165,000',
      requirements: "Bachelor's degree in Hospitality Management or related field, extensive hospitality experience",
      education: "Bachelor's degree",
      growth: 'Average (4%)',
      dayInLife: 'Manage daily hotel operations, oversee departments, handle guest complaints, monitor budgets, and ensure service quality standards.',
      dayInLifeList: [
        'Oversee all hotel departments',
        'Manage budgets and financial performance',
        'Resolve guest complaints and issues',
        'Hire and train staff',
        'Ensure facility maintenance',
        'Develop marketing strategies',
      ],
      onetCode: '11-9081.00',
    },
    {
      title: 'Event Coordinator',
      description: 'Plan and execute events including conferences, weddings, corporate functions, and social gatherings from concept to completion.',
      avgSalary: '$52,000',
      salaryRange: '$35,000 - $81,000',
      requirements: "Bachelor's degree in Event Management, Hospitality, or related field, CMP (Certified Meeting Professional) certification beneficial",
      education: "Bachelor's degree",
      growth: 'Faster than average (8%)',
      dayInLife: 'Meet with clients, develop event concepts, coordinate vendors, manage budgets, oversee event setup, and ensure smooth event execution.',
      dayInLifeList: [
        'Consult with clients on event vision',
        'Develop event plans and timelines',
        'Book venues and coordinate vendors',
        'Manage event budgets',
        'Oversee event setup and execution',
        'Handle day-of logistics and troubleshooting',
      ],
      onetCode: '13-1121.00',
    },

    // Agriculture & Environmental
    {
      title: 'Agricultural Engineer',
      description: 'Design and develop agricultural equipment, systems, and structures to improve farming efficiency and sustainability.',
      avgSalary: '$84,000',
      salaryRange: '$58,000 - $121,000',
      requirements: "Bachelor's degree in Agricultural Engineering or Biological Engineering, PE license beneficial",
      education: "Bachelor's degree",
      growth: 'Average (5%)',
      dayInLife: 'Design farm machinery, develop irrigation systems, create solutions for crop storage and processing, and improve agricultural sustainability.',
      dayInLifeList: [
        'Design agricultural equipment and systems',
        'Develop irrigation and drainage systems',
        'Test and refine machinery prototypes',
        'Consult with farmers on equipment needs',
        'Ensure compliance with environmental standards',
        'Research sustainable farming technologies',
      ],
      onetCode: '17-2021.00',
    },
    {
      title: 'Park Ranger',
      description: 'Protect and preserve natural and cultural resources in national and state parks while providing visitor services and education.',
      avgSalary: '$48,000',
      salaryRange: '$33,000 - $75,000',
      requirements: "Bachelor's degree in Park and Recreation Management, Environmental Science, or related field, law enforcement training for protection rangers",
      education: "Bachelor's degree",
      growth: 'Average (3%)',
      dayInLife: 'Patrol park areas, educate visitors, enforce regulations, conduct search and rescue operations, and maintain park facilities.',
      dayInLifeList: [
        'Patrol park grounds and trails',
        'Provide visitor information and education',
        'Enforce park rules and regulations',
        'Conduct interpretive programs',
        'Assist with search and rescue',
        'Monitor wildlife and ecosystems',
      ],
      onetCode: '33-9092.00',
    },
    {
      title: 'Food Scientist',
      description: 'Research and develop new food products, improve food processing methods, and ensure food safety and quality.',
      avgSalary: '$74,000',
      salaryRange: '$49,000 - $118,000',
      requirements: "Bachelor's degree in Food Science, Chemistry, or related field, advanced degree for research positions",
      education: "Bachelor's degree",
      growth: 'Faster than average (7%)',
      dayInLife: 'Develop new food formulations, test product stability, ensure regulatory compliance, analyze nutritional content, and improve production processes.',
      dayInLifeList: [
        'Develop new food product formulations',
        'Test food safety and shelf life',
        'Analyze nutritional content',
        'Ensure regulatory compliance',
        'Improve food processing methods',
        'Conduct sensory evaluations',
      ],
      onetCode: '19-1012.00',
    },

    // Transportation & Logistics
    {
      title: 'Air Traffic Controller',
      description: 'Coordinate aircraft movements to ensure safe and efficient flow of air traffic in airports and airspace.',
      avgSalary: '$138,000',
      salaryRange: '$72,000 - $184,000',
      requirements: 'FAA Academy training, passing medical and security clearances, U.S. citizenship required',
      education: 'Specialized FAA training',
      growth: 'Average (1%)',
      dayInLife: 'Monitor aircraft positions, issue takeoff and landing clearances, coordinate flight paths, manage traffic flow, and respond to emergencies.',
      dayInLifeList: [
        'Monitor radar screens for aircraft positions',
        'Issue clearances for takeoffs and landings',
        'Coordinate flight paths to prevent collisions',
        'Manage air traffic during weather events',
        'Communicate with pilots continuously',
        'Handle emergency situations',
      ],
      onetCode: '53-2021.00',
    },
    {
      title: 'Logistics Analyst',
      description: 'Analyze and optimize supply chain operations, transportation routes, and inventory management to improve efficiency and reduce costs.',
      avgSalary: '$78,000',
      salaryRange: '$54,000 - $115,000',
      requirements: "Bachelor's degree in Supply Chain Management, Business, or related field, APICS certification beneficial",
      education: "Bachelor's degree",
      growth: 'Much faster than average (28%)',
      dayInLife: 'Analyze logistics data, optimize transportation routes, forecast demand, coordinate with suppliers, and develop strategies to improve efficiency.',
      dayInLifeList: [
        'Analyze supply chain data',
        'Optimize transportation and distribution',
        'Forecast inventory needs',
        'Track shipments and deliveries',
        'Identify cost-saving opportunities',
        'Create logistics reports',
      ],
      onetCode: '13-1081.02',
    },

    // Emerging & Specialized
    {
      title: 'Drone Pilot',
      description: 'Operate unmanned aerial vehicles (UAVs) for commercial purposes including photography, surveying, inspection, and delivery.',
      avgSalary: '$65,000',
      salaryRange: '$42,000 - $98,000',
      requirements: 'FAA Part 107 Remote Pilot Certificate, passing aeronautical knowledge test',
      education: 'Certification required',
      growth: 'Much faster than average (emerging field)',
      dayInLife: 'Plan flight missions, operate drones for various applications, capture aerial footage, conduct inspections, and ensure FAA compliance.',
      dayInLifeList: [
        'Plan and coordinate flight operations',
        'Conduct pre-flight drone inspections',
        'Operate drones for photography or surveying',
        'Process and edit captured data',
        'Maintain and repair drone equipment',
        'Ensure FAA regulatory compliance',
      ],
      onetCode: '53-2012.00',
    },
    {
      title: 'Virtual Reality Developer',
      description: 'Create immersive virtual reality experiences and applications for gaming, training, education, and simulation.',
      avgSalary: '$98,000',
      salaryRange: '$68,000 - $145,000',
      requirements: "Bachelor's degree in Computer Science or Game Development, expertise in Unity/Unreal Engine, 3D modeling",
      education: "Bachelor's degree",
      growth: 'Much faster than average (emerging field)',
      dayInLife: 'Develop VR applications, create 3D environments, implement VR interactions, optimize performance, and test VR experiences.',
      dayInLifeList: [
        'Design VR experiences and interactions',
        'Develop 3D environments and assets',
        'Program VR functionality',
        'Optimize VR performance',
        'Test and debug VR applications',
        'Collaborate with designers and artists',
      ],
      onetCode: '15-1255.00',
    },
    {
      title: 'Podcast Producer',
      description: 'Plan, record, edit, and distribute podcast episodes, managing all aspects of podcast creation and distribution.',
      avgSalary: '$61,000',
      salaryRange: '$38,000 - $98,000',
      requirements: 'Audio production skills, expertise in recording and editing software, content creation experience',
      education: 'Variable (often Bachelor\'s degree)',
      growth: 'Faster than average (emerging field)',
      dayInLife: 'Develop episode concepts, schedule and record interviews, edit audio, write show notes, and manage podcast distribution.',
      dayInLifeList: [
        'Plan episode topics and guest interviews',
        'Schedule and conduct recordings',
        'Edit audio and add music/effects',
        'Write show notes and descriptions',
        'Publish episodes to podcast platforms',
        'Promote podcast on social media',
      ],
      onetCode: '27-2012.00',
    },
  ];

  let saved = 0;
  let skipped = 0;

  for (const career of careers) {
    try {
      // Check if career already exists
      const existing = await prisma.career.findFirst({
        where: { title: career.title },
      });

      if (existing) {
        console.log(`⏭️  Skipped (already exists): ${career.title}`);
        skipped++;
        continue;
      }

      await prisma.career.create({
        data: career,
      });

      console.log(`✓ Added: ${career.title}`);
      saved++;
    } catch (error) {
      console.error(`✗ Failed to add ${career.title}:`, error);
    }
  }

  const totalCareers = await prisma.career.count();

  console.log('\n✅ Additional career seeding completed!');
  console.log(`📊 Careers saved: ${saved}`);
  console.log(`⏭️  Duplicates skipped: ${skipped}`);
  console.log(`💾 Total careers in database: ${totalCareers}`);
}

main()
  .catch((e) => {
    console.error('Error seeding careers:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
